# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  ########################################
  ### RESOURCES: Installation of Windows Packages
  ########################################
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: git
      directives:
        description: Install Git
        allowPrerelease: false
      settings:
        id: Git.Git

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Node JS
        allowPrerelease: false
      settings:
        id: OpenJS.NodeJS.LTS
        version: 20.18.1

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Yarn
        allowPrerelease: false
      settings:
        id: Yarn.Yarn
        version: 1.22.22

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: JetBrains IntelliJ IDEA Community
        allowPrerelease: false
      settings:
        id: JetBrains.IntelliJIDEA.Community 

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Notepad++
        allowPrerelease: false
      settings:
        id: Notepad++.Notepad++

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Java JDK 17
        allowPrerelease: false
      settings:
        id: Oracle.JDK.17

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Java JDK 21
        allowPrerelease: false
      settings:
        id: Oracle.JDK.21

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: MongoDB Compass
        allowPrerelease: false
      settings:
        id: MongoDB.Compass.Full

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Google Chrome
        allowPrerelease: false
      settings:
        id: Google.Chrome

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Mozilla Firefox
        allowPrerelease: false
      settings:
        id: Mozilla.Firefox

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      directives:
        description: Install Visual Studio Code
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode
        ensure: Present

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: OpenSSL
        allowPrerelease: false
      settings:
        id: ShiningLight.OpenSSL.Dev

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Bruno
        allowPrerelease: false
      settings:
        id: Bruno.Bruno

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install KeyStore Explorer
        allowPrerelease: false
      settings:
        id: KaiKramer.KeyStoreExplorer
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: RedisInsight
      directives:
        description: Install RedisInsight
        allowPrerelease: false
      settings:
        id: XP8K1GHCB0F1R2
        source: msstore

    ##########################################
    ### RESOURCES: Visual Studio Code Extensions
    ##########################################

    # - resource: Microsoft.VSCode.Dsc/VSCodeExtension
    #   id: github.copilot
    #   dependsOn: vscode
    #   directives:
    #     description: Install GitHub Copilot
    #     allowPrerelease: true
    #   settings:
    #     name: github.copilot
    #     exist: true

    # - resource: Microsoft.VSCode.Dsc/VSCodeExtension
    #   id: github.copilot-chat 
    #   dependsOn: vscode
    #   directives:
    #     description: Install GitHub Copilot Chat
    #     allowPrerelease: true
    #   settings:
    #     name: github.copilot-chat
    #     exist: true

    # - resource: Microsoft.VSCode.Dsc/VSCodeExtension
    #   id: GitLab.gitlab-workflow
    #   dependsOn: vscode
    #   directives:
    #     description: Install GitLab Workflow
    #     allowPrerelease: true
    #   settings:
    #     name: GitLab.gitlab-workflow
    #     exist: true